
TEST_NAME=mpn
OBJECTS  = $(TGT_DIR)/$(TEST_NAME).o \
           $(TGT_DIR)/boot.o \
           $(LIBSCARV)/lib/mpn_add.o \
           $(LIBSCARV)/lib/mpn_sub.o \
           $(LIBSCARV)/lib/mpn_mul.o \

include ../common/common.mk
