+incdir+$(XC_HOME)/rtl/coprocessor
$(XC_HOME)/rtl/coprocessor/scarv_cop_aes_sbox.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_aes.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_cprs.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_idecode.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_palu.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_palu_adder.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_palu_shifter.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_palu_multiplier.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_malu.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_rng.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_mem.v
$(XC_HOME)/rtl/coprocessor/scarv_cop_top.v
$(XC_HOME)/rtl/integration/scarv_integ_prv_pcpi2cop.v
$(XC_HOME)/rtl/integration/scarv_prv_xcrypt_top.v
$(XC_HOME)/external/picorv32/picorv32.v
$(XC_HOME)/verif/tb/axi_sram.v
$(XC_HOME)/verif/tb/tb_integration.v
