

TEST_NAME=helloworld
OBJECTS  = $(TGT_DIR)/$(TEST_NAME).o \
           $(TGT_DIR)/boot.o \
           $(LIBSCARV)/lib/mpn_add.o \
           $(LIBSCARV)/lib/mpn_add_xc.o

include ../common/common.mk
