



xc.sha3.xy a2, t0, t1, 0
xc.sha3.xy a2, t0, t1, 1
xc.sha3.xy a2, t0, t1, 2
xc.sha3.xy a2, t0, t1, 3

xc.sha3.x1 a2, t0, t1, 0
xc.sha3.x1 a2, t0, t1, 1
xc.sha3.x1 a2, t0, t1, 2
xc.sha3.x1 a2, t0, t1, 3

xc.sha3.x2 a2, t0, t1, 0
xc.sha3.x2 a2, t0, t1, 1
xc.sha3.x2 a2, t0, t1, 2
xc.sha3.x2 a2, t0, t1, 3

xc.sha3.x4 a2, t0, t1, 0
xc.sha3.x4 a2, t0, t1, 1
xc.sha3.x4 a2, t0, t1, 2
xc.sha3.x4 a2, t0, t1, 3

xc.sha3.yx a2, t0, t1, 0
xc.sha3.yx a2, t0, t1, 1
xc.sha3.yx a2, t0, t1, 2
xc.sha3.yx a2, t0, t1, 3
